services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    environment:
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8000
    ports:
      - "8000:8000"

  client:
    depends_on:
      - server
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    environment:
      - MCP_SERVER_URL=http://server:8000/mcp/
    # Use a shell command to run the client.py script in a loop
    entrypoint: sh
    command: >
      -c "while true; do
        uv run client.py
      done;"